

# #+NAME: Assign DNS address

apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: ii.coop
spec:
  endpoints:
  - dnsName: ns1.ii.coop
    recordTTL: 3600
    recordType: A
    targets:
    - ${LOAD_BALANCER_IP}
  - dnsName: ii.coop
    recordTTL: 3600
    recordType: NS
    targets:
    - ns1.ii.coop
