

# #+NAME: DNSEndpoint

apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: gitlab-ii-coop
spec:
  endpoints:
  - dnsName: 'gitlab2.ii.coop'
    recordTTL: 3600
    recordType: A
    targets:
    - ${LOAD_BALANCER_IP}
  - dnsName: '*.gitlab2.ii.coop'
    recordTTL: 3600
    recordType: A
    targets:
    - ${LOAD_BALANCER_IP}
  - dnsName: gitlab2.ii.coop
    recordTTL: 3600
    recordType: SOA
    targets:
    - 'ns1.gitlab2.ii.coop. hostmaster.gitlab2.ii.coop. 5 3600 3600 3600 3600'
