

# #+NAME: Postgres operator

apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: postgres-operator
spec:
  releaseName: postgres-operator
  chart:
    git: https://github.com/zalando/postgres-operator
    ref: v1.6.0
    path: charts/postgres-operator
