apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rook-ceph-pvc-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: rook-ceph-block
