# Running as a Kubernetes CronJob

# Define the CronJob

apiVersion: batch/v1
kind: CronJob
metadata:
  name: asn-etl-pipeline
  labels:
    app: asn-etl-pipeline
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      name: asn-etl-pipeline
    spec:
      parallelism: 1
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: asn-etl-pipeline
        spec:
          restartPolicy: Never
          containers:
            - name: asn-etl-pipeline
              image: asn-etl-pipeline
              imagePullPolicy: Never
              volumeMounts:
                - name: gcp-app-creds
                  mountPath: /etc/asn-etl-pipeline
              env:
                - name: POSTGRES_PASSWORD
                  value: postgres
                - name: GCP_PROJECT
                  value: k8s-infra-ii-sandbox
                - name: GCP_SERVICEACCOUNT
                  value: asn-etl@k8s-infra-ii-sandbox.iam.gserviceaccount.com
                - name: GCP_BIGQUERY_DATASET
                  value: etl_script_generated_set
                - name: GCP_BIGQUERY_DATASET_LOGS
                  value: etl_script_generated_set_prod
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /etc/asn-etl-pipeline/asn-etl-pipeline-gcp-sa.json
                - name: ASN_DATA_PIPELINE_RETAIN
                  value: "false"
          volumes:
            - name: gcp-app-creds
              secret:
                secretName: gcp-app-creds
