apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsmasq
  namespace: dnsmasq
  labels:
    nz.ii: dnsmasq
    app: dnsmasq
spec:
  strategy:
    type: Recreate
  replicas: 3
  selector:
    matchLabels:
      nz.ii: dnsmasq
  template:
    metadata:
      annotations:
        nz.ii/dnsmasq.conf-sha256sum: "${DNSMASQ_CONF_HASH}"
        nz.ii/dockerfile-sha256sum: "${DOCKERFILE_HASH}"
      labels:
        nz.ii: dnsmasq
        app: dnsmasq
    spec:
      hostNetwork: true
      containers:
      - name: dnsmasq
        image: registry.gitlab.com/ii/nz/dnsmasq:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
              - SYS_ADMIN
          privileged: true
        ports:
        - containerPort: 67
          hostPort: 67
          protocol: UDP
