apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsmasq
  namespace: dnsmasq
spec:
  replicas: 3
  selector:
    matchLabels:
      nz.ii: dnsmasq
  template:
    metadata:
      labels:
        nz.ii: dnsmasq
    spec:
      allowPrivilegeEscalation: true
      allowedCapabilities:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
      hostNetwork: true
      hostPorts:
      - max: 7472
        min: 7472
      privileged: true
    spec:
      containers:
      - name: dnsmasq
        image: registry.gitlab.com/ii/nz/dnsmasq:latest
        ports:
        - containerPort: 67
          hostPort: 67
          protocol: UDP
